name: Release

on:
  push:
    branches:
      - main

env:
  imageRegistry: boehringeringelheim.azurecr.io
  imageRepository: boehringeringelheim

jobs:
  push_to_registry:
    name: Push Docker image to ACR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Login con las credenciales del registro de contenedores
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.imageRegistry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Construir el contenedor y subirlo al registro
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.imageRegistry }}/${{ env.imageRepository }}:latest