[theme]

# Primary accent for interactive elements
primaryColor = '#8CB48D'

# Background color for the main content area
backgroundColor = '#FFFAFD'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFFAFD'

# Color used for almost all text
textColor = '#043332'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"